name: linux-tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install inotify-tools acl
    - name: Execute tests and generate coverage report
      run: |
        export RUNNING_ON_GITHUB_ACTIONS=true
        export SSH_PORT=22
        echo "Running on github actions: ${RUNNING_ON_GITHUB_ACTIONS}"
        echo "Running on ssh port ${SSH_PORT}"
        sudo -E bash ./dev/tests/run_tests.sh
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
